# Many of the defaults are fine for our use.
# Members are case-sensitive
# http://docs.pullapprove.com/yaml/
approve_by_comment: true
reset_on_reopened: true
approve_regex: '^Approve'
reject_regex: '^Needs Change'
reviewers:
    required: 1
    members:
      - Blackbaud-BobbyEarl
      - blackbaud-johnly
      - Blackbaud-PatrickOFriel
      - Blackbaud-PaulCrowder
      - Blackbaud-ToddRoberts
